[package]
name = "mildew-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
umwelt.workspace = true
async-nats.workspace = true
tokio.workspace = true
quinn.workspace = true
rcgen.workspace = true
postcard.workspace = true
serde.workspace = true
